project:
  type: website
  output-dir: docs

website:
  title: "Welcome!"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/AdelineJerome/seminars-for-esa
    contents:
      - href: index.qmd
        text: Home
      - section: "Programming languages"
        contents:
          - python.qmd
          - rstat.qmd
      - section: "Doing LCA"
        contents:
          - ab_page.qmd
          - brightway_page.qmd
      - href: git_page.qmd
        text: Save your work - Git
      - section: "Seminars"
        contents:
          - seminar_intro.qmd
          - seminar_ab.qmd
          - seminar_brightway.qmd
          - seminar_git.qmd
      - section: "More"
        contents:
          - about.qmd
          - contribute.qmd
          - contact.qmd


format:
  html:
    theme:
        light: cosmo
        dark: superhero
    css: styles.css
    toc: true

editor: visual

