project:
  type: website
  output-dir: docs

website:
  title: "seminars-for-esa"
  navbar:
    background: light
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: installation_instructions.qmd
        text: Installation guide
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

