---
title: "Code-along with Brightway"
---

# Pre-seminar installation tasks

For this seminar, you should have a working Brightway environment on your computer. For this, you need to:

1.  If not already done, [install](seminar_brightway.qmd#installing-python-with-anaconda) Python and a Python environment manager,
2.  [Install](seminar_brightway.qmd#installing-brightway) or update Brightway.

## Installing Python with Anaconda

If you already have Python installed, skip this step. Otherwise, [follow this link](https://www.anaconda.com/download/) to download Anaconda. Follow the installation instructions of the installer.

### (Optional - Mamba)

If you think that you will use Python in the future, I recommend installing and using [Mamba](https://mamba.readthedocs.io/en/latest/index.html). It is much faster for "solving environments", i.e., for installing or updating packages, and for creating new environments. For installing it, open an "Anaconda prompt" and use the command recommended [here](https://anaconda.org/conda-forge/mamba):

``` python
conda install -c conda-forge mamba
```

## Installing Brightway

Open an "Anaconda prompt" (on Windows, you find it in the Start menu) and follow the [instructions for installing](https://docs.brightway.dev/en/latest/content/installation/index.html) Brightway.

# Seminar content

## Slides

<div>

```{=html}
<iframe class="slide-deck" height="300" width="500" style="border:2px solid black;" src="presentations/presentation_seminar_bright.html"></iframe>
```

</div>

> [**Link to the slides**](presentations/presentation_seminar_bright.html)

## Notebooks

For this seminar, the participants write and run code one Jupyter notebooks. These notebooks are available below.

> [Download the notebook](resources/brightway_seminar.ipynb) for doing a first LCA with brightway

> [Download the notebook](resources/basics_of_python.ipynb) with Python basics

> [Download the notebook solution](resources/brightway_seminar_solution.ipynb) for doing a first LCA with brightway
