---
title: "Code-along with the AB"
---

# Pre-seminar installation tasks

For this seminar, you should have the Activity Browser running on your computer and a project with ecoinvent open. For this, you need to:

1.  If not already done, [install](seminar_ab.qmd#installing-python-with-anaconda) Python and a Python environment manager,
2.  [Install](seminar_ab.qmd#installing-the-activity-browser) or update the Activity Browser,
3.  [Create a project](seminar_ab.qmd#create-an-lca-project-on-the-ab) with ecoinvent 3.9.1 cutoff.

## Installing Python with Anaconda

If you already have Python installed, skip this step. Otherwise, [follow this link](https://www.anaconda.com/download/) to download Anaconda. Follow the installation instructions of the installer.

## Installing the Activity Browser

Open an "Anaconda prompt" (on Windows, you find it on the Start menu) and follow the [instructions for installing](https://github.com/LCA-ActivityBrowser/activity-browser#installation) the Activity Browser, using the section *The thorough way*.

## Create an LCA project on the AB

Follow the [instructions on this page](https://github.com/LCA-ActivityBrowser/activity-browser#getting-started) to:

-   check that the AB starts on your computer,
-   create a new project:
    -   on the tab "Project", click on the button "+ New" and name the project (e.g., "ab_demo"),
    -   under "Databases", click on the button "Add default data (biosphere flows and impact categories)". This takes a few minutes.
    -   import the ecoinvent 3.9.1 cutoff database:
        -   Download from the AB (easiest): click on the button "Import", then "Import remote data (download)", "ecoinvent (requires login)", use the ESA login for ecoinvent, and then select version 3.9.1 and the system model "cutoff". The import takes a few minutes (longer than the step before).
        -   Otherwise, on [ecoquery from ecoinvent](https://ecoquery.ecoinvent.org/3.9.1/cutoff/files) download the 7z file "ecoinvent 3.9.3_cutoff_ecoSpold02.7z". On the AB, click on the button "Import", and then select "Import local data", "Local 7z-archive of ecospold2 files" and select the downloaded file.

# Seminar content

<div>

```{=html}
<iframe class="slide-deck" height="300" width="500" style="border:2px solid black;" src="presentations/presentation_seminar_ab.html"></iframe>
```

</div>

> [**Link to the slides**](presentations/presentation_seminar_ab.html)

## Introduction to Python environment management

The information presented is available [here](python.qmd#managing-python-virtual-environments).

## Introduction to the AB

::: callout-caution
## Work in progress

This section is still in development!
:::

## First LCA with the AB

As an example, we will reproduce a simplified version of the results in [Jerome et al. (2023)](https://doi.org/10.1016/j.resconrec.2023.107038). All the data are from the article and the supplementary information. The aim is the compare the LCA results for motors with different energy efficiency, and with and without their use extension with repair.

### LCA model construction

**Create a new database** by clicking on the button "+ New" besides "Databases". Name your database, e.g., `motor_case`.

The first activity that we will use is electricity production. Go to your ecoinvent database, search for the *market for electricity, high voltage* for Sweden (SE). Right click on the activity and choose "Duplicate activity to new location" to duplicate the activity to your new database.

**Create parameters** in the tab "Parameters". Create the following project parameters:

| Name                | Value | Description                                     |
|-----------------|-----------------|--------------------------------------|
| `steel_unalloyed`   | 26600 | Quantity (kg) of unalloyed steel in the motor   |
| `steel_low_alloyed` | 4100  | Quantity (kg) of low alloyed steel in the motor |
| `copper`            | 3600  | Quantity (kg) of copper in the motor            |
| `insulation`        | 400   | Quantity (kg) of insulation in the motor        |
| `output_power`      | 16000 | Output power (kW) of the motor                  |
| `op_hours`          | 8400  | Duration (hours) of operating time per year     |
| `lifetime`          | 20    | Lifetime (years) of the motor                   |
| `efficiency`        | 0.973 | Efficiency of the motor                         |

To **create new activities**, right click on the name of your new database and select "+ Add new activity". Create the following activities:

1.  *motor production*, producing 1 unit of motor, with:
    -   `steel_unalloyed` kg of *market for steel, unalloyed - GLO*
    -   `steel_low_alloyed` kg of *market for steel, low-alloyed - GLO*
    -   `copper` kg of *market for copper, cathode - GLO*
    -   `insulation` kg of *market for epoxy resin, liquid - RER*
    -   3600 kWh of electricity from the duplicated electricity activity
2.  *motor testing*, producing 1 unit of motor, tested, with:
    -   1 unit of motor from *motor production*
    -   16000 kWh of electricity from the duplicated electricity activity
3.  *motor use*, producing 1 unit of motor, used, with:
    -   1 unit of motor, tested from *motor testing*
    -   electricity from the duplicated electricity activity and using the formula `output_power*op_hours*lifetime*(1/efficiency-1)` for having only the energy losses during the use of the motor
4.  *motor EoL treatment*, producing 1 unit of motor, treated, with:
    -   1 unit of motor, used from *motor use*
    -   `0.041*(steel_unalloyed+steel_low_alloyed+copper+insulation)` of electricity from the duplicated electricity activity
    -   `insulation` kg of *treatment of waste plastic, mixture, municipal incineration with fly ash extraction - CH*
    -   `0.04*copper` kg of *treatment of copper in car shredder residue, municipal incineration with fly ash extraction - CH*

### Motor efficiency scenarios

In the tab "Parameters", select the tab "Scenarios". Click on the button "Export parameter-scenarios" to download the Excel file format for generating scenarios.

Create the following scenarios:

| Name              | low_efficiency | high_efficiency | repair_low_efficiency | repair_high_efficiency |
| ----------------- | -------------- | --------------- | --------------------- | ---------------------- |
| steel_unalloyed   | 26600          | 18000           | 26600                 | 18000                  |
| steel_low_alloyed | 4100           | 9200            | 4100                  | 9200                   |
| copper            | 3600           | 3800            | 5400                  | 5700                   |
| insulation        | 400            | 300             | 600                   | 450                    |
| output_power      | 16000          | 16000           | 16000                 | 16000                  |
| op_hours          | 8400           | 8400            | 8400                  | 8400                   |
| lifetime          | 20             | 20              | 40                    | 40                     |
| efficiency        | 0,973          | 0,9835          | 0,973                 | 0,9835                 |



### Bonus - Future electricity mixes scenarios
